---
# Based on Jeff Geerling's testing
# For example:
# https://github.com/geerlingguy/ansible-role-kibana/blob/master/.travis.yml

language: python
services: docker

env:
  global:
    - ROLE_NAME: docker-ce
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - pwd
  - ls -la
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
