---
# handlers file for docker

- name: start docker
  systemd:
    name: docker
    state: started
  become: true
  become_user: root

- name: enable docker
  systemd:
    name: docker
    enabled: true
  become: true
  become_user: root
